
services:
  lamarquetech_site:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: lamarquetech_site

    restart: unless-stopped

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.lamarquetech.rule=Host(`lamarquetech.com.br`) || Host(`www.lamarquetech.com.br`)"
      - "traefik.http.routers.lamarquetech.entrypoints=websecure"
      - "traefik.http.routers.lamarquetech.tls.certresolver=letsencrypt"
      - "traefik.http.services.lamarquetech.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
